## ML-Evaluating_Model

## Loading the Model

In [10]:
# Importing Dependencies

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os
from tensorflow.keras.models import Sequential, save_model, load_model


In [11]:
# Load the model
from tensorflow.keras.models import load_model
model = load_model("models/ml_model_earthquakedata_20k.h5", compile = True)

In [12]:
# Load the Prediction File 

prediction_file = pd.read_csv("data_base/earthquakes_predition_12k.csv")
prediction_file.head()


date  latitude  longitude
0  20160206       -30       -178
1  20160207        33         48
2  20160207        44        149
3  20160207        -3        128
4  20160207        32        141

In [13]:
# Add sample to array for prediction

pred_data_set = prediction_file.to_numpy()
pred_data_set

array([[20160206,      -30,     -178],
       [20160207,       33,       48],
       [20160207,       44,      149],
       ...,
       [20201022,       20,      -77],
       [20201031,      -14,      167],
       [20201214,      -57,      -26]], dtype=int64)

In [14]:
# Generate predictions for samples
predictions = model.predict(pred_data_set)
print(predictions)

[[0. 1.]
 [0. 1.]
 [0. 1.]
 ...
 [0. 1.]
 [0. 1.]
 [0. 1.]]


In [15]:
# Generate arg maxes for predictions
classes = np.argmax(predictions, axis = 1)
print(classes)

[1 1 1 ... 1 1 1]
